# Parameters for Meshy 3D API
# For more details see https://meshy.com/docs/api-reference

endpoint: "https://api.meshy.com/v1/generate"
method: "POST"
headers:
  Authorization: "Bearer $3D_MODEL_API_KEY"
  Content-Type: "application/json"
requiredParameters:
  prompt:
    description: "A text description of the desired 3D asset(s)."
    options: [] 
optionalParameters:
  model:
    default: "meshy-v2"
    description: "The model to use for 3D asset generation."
    options: ["meshy-v1", "meshy-v2"]
  n:
    default: 1
    description: "The number of 3D assets to generate. Must be between 1 and 5."
    options: [1, 2, 3, 4, 5]
  quality:
    default: "standard"
    description: "The quality of the generated 3D model."
    options: ["standard", "high"]
  response_format:
    default: "url"
    description: "The format in which the generated 3D models are returned."
    options: ["url", "obj", "gltf"]
  size:
    default: "medium"
    description: "The scale of the generated 3D model."
    options: ["small", "medium", "large"]
  style:
    default: "realistic"
    description: "The style of the generated 3D model."
    options: ["realistic", "cartoon", "low-poly"]
  user:
    description: "A unique identifier representing your end-user."
    options: [] 
