name: Go CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-check:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4' # Specify the Go version you are using

    - name: Install gopls
      run: go install golang.org/x/tools/gopls@latest

    - name: Run gopls for linting
      run: gopls check ./...

    - name: Check formatting with gofmt
      run: |
        files=$(gofmt -l .)
        if [ -n "$files" ]; then
          echo "The following files are not formatted correctly:"
          echo "$files"
          exit 1
        fi

