endpoint: "https://api.lumalabs.ai/dream-machine/v1/generations"
method: "POST"
headers:
  accept: "application/json"
  authorization: "Bearer &VIDEO_API_KEY"
  content-Type: "application/json"
requiredParameters:
  prompt:
    description: "A text description of the desired video."
    options: [] 
  model:
    default: "ray-2"
  resolution: 
    default: "540p"
  duration:
    default: "5s"
  generation_type:
    default: "video"
# optionalParameters:
#   width:
#     default: 1024
#     description: "Width of the generated video in pixels."
#     options: [512, 768, 1024]
#   height:
#     default: 576
#     description: "Height of the generated video in pixels."
#     options: [512, 576, 720]
#   duration:
#     default: 4
#     description: "Duration of the generated video in seconds."
#     options: [1, 2, 3, 4, 5, 6]
#   motion:
#     default: "cinematic"
#     description: "The style of camera motion applied to the video."
#     options: ["cinematic", "steady", "handheld"]
#   model:
#     default: "gen-1"
#     description: "The model to use for video generation."
#     options: ["gen-1", "gen-2"]
#   aspect_ratio:
#     default: "16:9"
#     description: "Aspect ratio of the generated video."
#     options: ["16:9", "9:16", "1:1"]
#   fps:
#     default: 24
#     description: "Frames per second of the generated video."
#     options: [12, 24, 30]
#   seed:
#     default: null
#     description: "Seed for randomization; leave null for random results."
#     options: []
#   response_format:
#     default: "url"
#     description: "The format in which the generated video is returned."
#     options: ["url"]
