#For more details see https://platform.openai.com/docs/api-reference/images/create

image:
  steps:
    - name: "generate_image"
      method: "POST"
      url: "https://api.openai.com/v1/images/generations"
      headers:
        Authorization: "Bearer &OPENAI_API_KEY"
        Content-Type: "application/json"
      body:
        intent_detection_step: true
      response_key: "data"
      content_extraction:
        response_path: "data.0.url"
        response_format: "url"
        file_extention: "png"
