video:
  steps:
    - name: "submit_text_to_video_generation"
      method: "POST"
      url: "https://api.lumalabs.ai/dream-machine/v1/generations"
      headers:
        Authorization: "Bearer &LUMA_API_KEY"
        Content-Type: "application/json"
      body:
        intent_detection_step: true
      response_placeholders:
        generation_id: id

    - name: "poll_video_generation_status"
      method: "GET"
      url: "https://api.lumalabs.ai/dream-machine/v1/generations/{generation_id}"
      headers:
        Authorization: "Bearer &LUMA_API_KEY"
      response_placeholders:
        status: state
      poll:
        until: "completed"
        interval: 10
      content_extraction:
         response_path: "assets.video"
         response_format: "url"
         file_extention: "mp4"

