endpoint: "https://api.openai.com/v1/chat/completions"
method: "POST"
initialPrompt: "Currently Empty, not sure the best way to store this info" #not sure how to best format this for our prompt
headers:
  Authorization: "Bearer $CHATGEN_API_KEY"
  Content-Type: "application/json"
body:
  message: "$UserInput" #how to replace this with the real user prompt
  model : "gpt-4o"