gif:
  steps:
    - name: "submit_image_generation"
      method: "POST"
      url: "https://cloud.leonardo.ai/api/rest/v1/generations"
      headers:
        Authorization: "Bearer &LEONARDO_API_KEY"
        Content-Type: "application/json"
      body:
        height: 768
        width: 1024
        modelId: "1e60896f-3c26-4296-8ecc-53e2afecc132"
        prompt: "{user_input}"  # First user prompt (for image generation)
        num_images: 1
        alchemy: true
      response_placeholders:
        generation_id: sdGenerationJob.generationId

    - name: "poll_image_generation_status"
      method: "GET"
      url: "https://cloud.leonardo.ai/api/rest/v1/generations/{generation_id}"
      headers:
        Authorization: "Bearer &LEONARDO_API_KEY"
      response_placeholders:
        status: status
        image_id: generations_by_pk.generated_images.0.id
      poll:
        until: "SUCCEEDED"
        interval: 10

    - name: "submit_motion_generation"
      method: "POST"
      url: "https://cloud.leonardo.ai/api/rest/v1/generations-motion-svd"
      headers:
        Authorization: "Bearer &LEONARDO_API_KEY"
        Content-Type: "application/json"
      body:
        imageId: "{image_id}"
        motionStrength: 5  # Can be adjusted based on user preference
      response_placeholders:
        motion_generation_id: motionSvdGenerationJob.generationId

    - name: "poll_motion_generation_status"
      method: "GET"
      url: "https://cloud.leonardo.ai/api/rest/v1/generations/{motion_generation_id}"
      headers:
        Authorization: "Bearer &LEONARDO_API_KEY"
      response_placeholders:
        status: status
        video_url: generations_by_pk.generated_video.url
      poll:
        until: "SUCCEEDED"
        interval: 10

    - name: "fetch_final_video"
      method: "GET"
      url: "{video_url}"
      headers:
        Authorization: "Bearer &LEONARDO_API_KEY"
      response_placeholders:
        response_path: "output.video_url"
        response_format: "url"
        file_id_path: "id"
        file_extention: "jpg" # The final motion video file
