gif:
  steps:
    - name: "submit_image_generation"
      method: "POST"
      url: "https://cloud.leonardo.ai/api/rest/v1/generations"
      headers:
        Authorization: "Bearer &GIF_API_KEY"
        Content-Type: "application/json"
      body:
        intent_detection_step: true
      response_placeholders:
        generation_id: sdGenerationJob.generationId

    - name: "poll_image_generation_status"
      method: "GET"
      url: "https://cloud.leonardo.ai/api/rest/v1/generations/{generation_id}"
      headers:
        Authorization: "Bearer &GIF_API_KEY"
      response_placeholders:
        status: generations_by_pk.status
        image_id: generations_by_pk.generated_images.0.id
      poll:
        until: "COMPLETE"
        interval: 10

    - name: "submit_motion_generation"
      method: "POST"
      url: "https://cloud.leonardo.ai/api/rest/v1/generations-motion-svd"
      headers:
        Authorization: "Bearer &GIF_API_KEY"
        Content-Type: "application/json"
      body:
        imageId: "{image_id}"
      response_placeholders:
        motion_generation_id: motionSvdGenerationJob.generationId

    - name: "poll_motion_generation_status"
      method: "GET"
      url: "https://cloud.leonardo.ai/api/rest/v1/generations/{motion_generation_id}"
      headers:
        Authorization: "Bearer &GIF_API_KEY"
      response_placeholders:
        status: generations_by_pk.status
      poll:
        until: "COMPLETE"
        interval: 10
      content_extraction:
        response_path: "generations_by_pk.generated_images.motionMP4URL" #should be this once 0 index gets fixed generations_by_pk.generated_images.0.motionMP4URL
        response_format: "url"
        file_extention: "mp4" 
        