gif:
  steps:
    - name: "submit_image_generation"
      method: "POST"
      url: "https://cloud.leonardo.ai/api/rest/v1/generations"
      headers:
        Authorization: "Bearer &GIF_API_KEY"
        Content-Type: "application/json"
      body:
        intent_detection_step: true
      response_placeholders:
        generation_id: sdGenerationJob.generationId

    - name: "poll_image_generation_status"
      method: "GET"
      url: "https://cloud.leonardo.ai/api/rest/v1/generations/{generation_id}"
      headers:
        Authorization: "Bearer &GIF_API_KEY"
      response_placeholders:
        status: generations_by_pk.status
        image_id: generations_by_pk.generated_images.0.id
      poll:
        until: "COMPLETE"
        interval: 10

    - name: "submit_motion_generation"
      method: "POST"
      url: "https://cloud.leonardo.ai/api/rest/v1/generations-motion-svd"
      headers:
        Authorization: "Bearer &GIF_API_KEY"
        Content-Type: "application/json"
      body:
        imageId: "{image_id}"
      response_placeholders:
        motion_generation_id: motionSvdGenerationJob.generationId

    - name: "poll_motion_generation_status"
      method: "GET"
      url: "https://cloud.leonardo.ai/api/rest/v1/generations/{motion_generation_id}"
      headers:
        Authorization: "Bearer &GIF_API_KEY"
      response_placeholders:
        status: generations_by_pk.status
        video_url: generations_by_pk.generated_images.0.motionMP4URL
      poll:
        until: "COMPLETE"
        interval: 10

    - name: "fetch_final_video"
      method: "GET"
      url: "{video_url}"
      response_placeholders:
        video_file: video_url  # The final motion video file
