#this is the 3d workflow pasted over for testing
video:
  steps:
    - name: "submit_preview_task"
      method: "POST"
      url: "https://api.meshy.ai/openapi/v2/text-to-3d"
      headers:
        Authorization: "Bearer $VIDEO_API_KEY"
        Content-Type: "application/json"
      body:
        mode: "preview"
        prompt: "{user_input}"
      response_placeholders:
        preview_task_id: result  # This is the only response we get from the API

    - name: "poll_preview_status"
      method: "GET"
      url: "https://api.meshy.ai/openapi/v2/text-to-3d/{preview_task_id}"
      headers:
        Authorization: "Bearer $VIDEO_API_KEY"
      response_placeholders:
        status: status
      poll:
        until: "SUCCEEDED"
        interval: 5

    - name: "submit_refine_task"
      method: "POST"
      url: "https://api.meshy.ai/openapi/v2/text-to-3d"
      headers:
        Authorization: "Bearer $VIDEO_API_KEY"
        Content-Type: "application/json"
      body:
        mode: "refine"
        preview_task_id: "{preview_task_id}"
      response_placeholders:
        refine_task_id: result  # This is the new task ID we need


    - name: "poll_refine_status"
      method: "GET"
      url: "https://api.meshy.ai/openapi/v2/text-to-3d/{refine_task_id}"
      headers:
        Authorization: "Bearer $VIDEO_API_KEY"
      response_placeholders:
        status: status
      poll:
        until: "SUCCEEDED"
        interval: 5

    - name: "fetch_final_model"
      method: "GET"
      url: "https://api.meshy.ai/openapi/v2/text-to-3d/{refine_task_id}"
      headers:
        Authorization: "Bearer $VIDEO_API_KEY"
      response_placeholders:
        model_url: model_urls.glb
