#For more details see https://platform.openai.com/docs/api-reference/images/create

image:
  steps:
    - name: "generate_image"
      method: "POST"
      url: "https://api.deepai.org/api/text2img"
      headers:
        api-key: "&DEEPAI_API_KEY"
        Content-Type: "application/json"
      body:
        intent_detection_step: true
      response_key: "data"
      content_extraction:
        response_path: "output_url"
        response_format: "url"
        file_extention: "jpg"