# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Build
      run: go build -v ./...

    - name: Run gofmt
      run: |
        files=$(gofmt -l .)
        if [ -n "$files" ]; then
          echo "The following files need formatting:"
          echo "$files"
          gofmt -w .
        else
          echo "No formatting issues found."
        fi

    - name: Commit and push changes
      if: success() && steps.format-code.outputs.changed == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "chore: auto-format code"
        git push

      #    - name: Test
      #      run: go test -v ./...
